name: Unit Tests
on:
  push:

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1.0.0
      -
        name: Install dependencies
        run: make arm_sdk_install gtest_install
      -
        name: Run all unit tests
        run: make all_ut_run
